
- name: Install basic packages
  action: apt pkg={{ item }} state=installed update_cache=yes
  with_items:
    - nginx

- name: Remove all default nginx configs
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Remove all default nginx configs
  file: dest=/etc/nginx/sites-available/default state=absent

- name: Make sure the /opt/mam-nginx/ directory exists
  file: dest=/opt/mam-nginx/ mode=755 state=directory owner={{ mamUID }} group={{ mamGID }}

- name: Set up nginx default site
  template: src=mam-api dest=/opt/mam-nginx/mam-api owner={{ mamUID }} group={{ mamGID }} mode=644

- name: enable the mam-api site
  file: src=/opt/mam-nginx/mam-api dest=/etc/nginx/sites-enabled/mam-api state=link

- name: Make sure the /opt/mam-nginx/certificates directory exists
  file: dest=/opt/mam-nginx/certificates mode=755 state=directory owner={{ mamUID }} group={{ mamGID }}

- name: Make sure the /opt/mam-nginx/logs directory exists
  file: dest=/opt/mam-nginx/logs mode=755 state=directory owner={{ mamUID }} group={{ mamGID }}

- name: Copy MAM SSL cert
  copy: src=mam.crt dest=/opt/mam-nginx/certificates/mam.crt

- name: Copy MAM SSL key
  copy: src=mam.key dest=/opt/mam-nginx/certificates/mam.key

- name: restart nginx
  service: name=nginx state=restarted