var React = require('react');

var HeaderLogout = require('../components/header-logout');

var Legal = React.createClass({
    render: function(){
        return (
            <div>
                <div className="header">
                    <HeaderLogout />
                </div>
                <div className="content-body">
                    <div className="content-body container">
                        <div className="panel panel-default bg-white">
                            <div className="panel-body no-pad-bottom">
                                <div className="row">
                                    <h2 className="bordered-bottom col-xs-12">Privacy Policy</h2>
                                </div>
                                <div className="row triple-gap-bottom double-gap-top">
                                    <p className="col-xs-12">Lorem ipsum dolor sit amet, consectetur adipiscing elit. An id exploratum cuiquam potest esse, quo modo se hoc habiturum sit corpus, non dico ad annum, sed ad vesperum? Duo enim genera quae erant, fecit tria. Ergo in iis adolescentibus bonam spem esse dicemus et magnam indolem, quos suis commodis inservituros et quicquid ipsis expediat facturos arbitrabimur? Et hercule mihi vir optimus nostrique amantissimus, Aulus Torquatus, versatur ante oculos, cuius quantum studium et quam insigne fuerit erga me temporibus illis, quae nota sunt omnibus, scire necesse est utrumque vestrum. Nunc vero, quoniam haec nos etiam tractare coepimus, suppeditabit nobis Atticus noster e thesauris suis quos et quantos viros! nonne melius est de his aliquid quam tantis voluminibus de Themista loqui? Duo Reges: constructio interrete. Quis Pullum Numitorium Fregellanum, proditorem, quamquam rei publicae nostrae profuit, non odit? Quodsi, ne quo incommodo afficiare, non relinques amicum, tamen, ne sine fructu alligatus sis, ut moriatur optabis. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Concinnus deinde et elegans huius, Aristo, sed ea, quae desideratur, a magno philosopho, gravitas, in eo non fuit;
                                        <br />
                                        <br />
                                        His similes sunt omnes, qui virtuti student levantur vitiis, levantur erroribus, nisi forte censes Ti. Quibus expositis facilis est coniectura ea maxime esse expetenda ex nostris, quae plurimum habent dignitatis, ut optimae cuiusque partis, quae per se expetatur, virtus sit expetenda maxime. Ita fit beatae vitae domina fortuna, quam Epicurus ait exiguam intervenire sapienti. Mihi quidem etiam lautius videtur, quod eligitur, et ad quod dilectus adhibetur -, sed, cum ego ista omnia bona dixero, tantum refert quam magna dicam, cum expetenda, quam valde. Quanta autem ab illis varietas argumentorum ratione concludentium eorumque cum captiosis interrogationibus dissimilitudo! Quid, quod plurimis locis quasi denuntiant, ut neque sensuum fidem sine ratione nec rationis sensibus exquiramus? Tum ille: Finem, inquit, interrogandi, si videtur, quod quidem ego a principio ita me malle dixeram hoc ipsum providens, dialecticas captiones.
                                        <br />
                                        <br />
                                        Nisi mihi Phaedrum, inquam, tu mentitum aut Zenonem putas, quorum utrumque audivi, cum mihi nihil sane praeter sedulitatem probarent, omnes mihi Epicuri sententiae satis notae sunt. Quis enim tam inimicus paene nomini Romano est, qui Ennii Medeam aut Antiopam Pacuvii spernat aut reiciat, quod se isdem Euripidis fabulis delectari dicat, Latinas litteras oderit? Aristoteles, Xenocrates, tota illa familia non dabit, quippe qui valitudinem, vires, divitias, gloriam, multa alia bona esse dicant, laudabilia non dicant. Inquit, cum ego te hac nova lege videam eodem die accusatori responderet tribus horis perorare, in hac me causa tempus dilaturum putas? Quamquam ex omnibus philosophis Stoici plurima novaverunt, Zenoque, eorum princeps, non tam rerum inventor fuit quam verborum novorum. Naturalem enim appetitionem, quam vocant o)rmh)n, itemque officium, ipsam etiam virtutem tuentem volunt esse earum rerum, quae secundum naturam sunt. An vero displicuit ea, quae tributa est animi virtutibus tanta praestantia? Atque omnia quidem scire, cuiuscumque modi sint, cupere curiosorum, duci vero maiorum rerum contemplatione ad cupiditatem scientiae summorum virorum est putandum. Et qui ipsi sibi bellum indixissent, cruciari dies, noctes torqueri vellent, nec vero sese ipsi accusarent ob eam causam, quod se male suis rebus consuluisse dicerent. Quis est enim, qui hoc cadere in sapientem dicere audeat, ut, si fieri possit, virtutem in perpetuum abiciat, ut dolore omni liberetur? Pungunt quasi aculeis interrogatiunculis angustis, quibus etiam qui assentiuntur nihil commutantur animo et idem abeunt, qui venerant. Tenesne igitur, inquam, Hieronymus Rhodius quid dicat esse summum bonum, quo putet omnia referri oportere? Ergo et avarus erit, sed finite, et adulter, verum habebit modum, et luxuriosus eodem modo. Si scieris, inquit Carneades, aspidem occulte latere uspiam, et velle aliquem inprudentem super eam assidere, cuius mors tibi emolumentum futura sit, improbe feceris, nisi monueris ne assidat, sed inpunite tamen;
                                        <br />
                                        <br />
                                        Ratio ista, quam defendis, praecepta, quae didicisti, quae probas, funditus evertunt amicitiam, quamvis eam Epicurus, ut facit, in caelum efferat laudibus. Omnium autem eorum commodorum, quibus non illi plus tribuunt, qui illa bona esse dicunt, quam Zeno, qui negat, longe praestantissimum esse, quod honestum esset atque laudabile. Re mihi non aeque satisfacit, et quidem locis pluribus. Sed lustremus animo non has maximas artis, quibus qui carebant inertes a maioribus nominabantur, sed quaero num existimes, non dico Homerum, Archilochum, Pindarum, sed Phidian, Polyclitum, Zeuxim ad voluptatem artes suas direxisse. Hominum non spinas vellentium, ut Stoici, nec ossa nudantium, sed eorum, qui grandia ornate vellent, enucleate minora dicere. Hoc foedus facere si potuerunt, faciant etiam illud, ut aequitatem, modestiam, virtutes omnes per se ipsas gratis diligant. Ratio ista, quam defendis, praecepta, quae didicisti, quae probas, funditus evertunt amicitiam, quamvis eam Epicurus, ut facit, in caelum efferat laudibus. Et si in ipsa gubernatione neglegentia est navis eversa, maius est peccatum in auro quam in palea. Non enim actionis aut officii ratio impellit ad ea, quae secundum naturam sunt, petenda, sed ab iis et appetitio et actio commovetur. Nam prius a se poterit quisque discedere quam appetitum earum rerum, quae sibi conducant, amittere. Atqui reperies, inquit, in hoc quidem pertinacem; Sic est igitur locutus: Quantus ornatus in Peripateticorum disciplina sit satis est a me, ut brevissime potuit, paulo ante dictum. Quod non subducta utilitatis ratione effici solet, sed ipsum a se oritur et sua sponte nascitur. Ad quorum et cognitionem et usum iam corroborati natura ipsa praeeunte deducimur. Nonne odio multos dignos putamus, qui quodam motu aut statu videntur naturae legem et modum contempsisse? Sed qui ad voluptatem omnia referens vivit ut Gallonius, loquitur ut Frugi ille Piso, non audio nec eum, quod sentiat, dicere existimo.
                                        <br />
                                        <br />
                                        Ea enim vita expetitur, quae sit animi corporisque expleta virtutibus, in eoque summum bonum poni necesse est, quandoquidem id tale esse debet, ut rerum expetendarum sit extremum. Idemque diviserunt naturam hominis in animum et corpus. Nos paucis ad haec additis finem faciamus aliquando; Nam illud quidem adduci vix possum, ut ea, quae senserit ille, tibi non vera videantur. Audio equidem philosophi vocem, Epicure, sed quid tibi dicendum sit oblitus es. Si enim sapiens aliquis miser esse possit, ne ego istam gloriosam memorabilemque virtutem non magno aestimandam putem. Conferam tecum, quam cuique verso rem subicias; Nam si dicent ab illis has res esse tractatas, ne ipsos quidem Graecos est cur tam multos legant, quam legendi sunt. Quae adhuc, Cato, a te dicta sunt, eadem, inquam, dicere posses, si sequerere Pyrrhonem aut Aristonem. Ac tamen, ne cui loco non videatur esse responsum, pauca etiam nunc dicam ad reliquam orationem tuam. Vide, ne etiam menses! nisi forte eum dicis, qui, simul atque arripuit, interficit. Maximeque eos videre possumus res gestas audire et legere velle, qui a spe gerendi absunt confecti senectute.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
});

module.exports = Legal;
