- hosts: production
  remote_user: root
  roles:
    - ubuntu
    - nodejs
    - mongodb
    - deploy
    - nginx-ssl
  vars:
      serverListenPort: "8090" # used by healthcheck
      nginxProxyToPort: "3000"
      applicationHostname: "www.docswap.co"
      nodeEnvironment: "production"
      adminContact: "adam@docswap.co"
      mamUID: "root"
      mamGID: "root"
      sslCertLocation: "production"
      sslCert: "docswap.crt"
      sslKey: "docswap.key"