- hosts: staging
  remote_user: root
  roles:
    - ubuntu
    - nodejs
    - mongodb
    - deploy
    - nginx-ssl
  vars:
      serverListenPort: "8090" # used by healthcheck
      nginxProxyToPort: "3000"
      applicationHostname: "mam-staging.neosavvy.com"
      adminContact: "contact@neosavvy.com"
      mamUID: "root"
      mamGID: "root"