module.exports = {
    usStates: [
        {data: "AK", label: "Alaska"},
        {data: "AL", label: "Alabama"},
        {data: "AR", label: "Arkansas"},
        {data: "AZ", label: "Arizona"},
        {data: "CA", label: "California"},
        {data: "CO", label: "Colorado"},
        {data: "CT", label: "Connecticut"},
        {data: "DE", label: "Delaware"},
        {data: "DC", label: "District of Columbia"},
        {data: "FL", label: "Florida"},
        {data: "GA", label: "Georgia"},
        {data: "HI", label: "Hawaii"},
        {data: "IA", label: "Iowa"},
        {data: "ID", label: "Idaho"},
        {data: "IL", label: "Illinois"},
        {data: "IN", label: "Indiana"},
        {data: "KS", label: "Kansas"},
        {data: "KY", label: "Kentucky"},
        {data: "LA", label: "Louisiana"},
        {data: "MA", label: "Massachusetts"},
        {data: "MD", label: "Maryland"},
        {data: "ME", label: "Maine"},
        {data: "MI", label: "Michigan"},
        {data: "MN", label: "Minnesota"},
        {data: "MS", label: "Mississippi"},
        {data: "MO", label: "Missouri"},
        {data: "MT", label: "Montana"},
        {data: "NC", label: "North Carolina"},
        {data: "ND", label: "North Dakota"},
        {data: "NE", label: "Nebraska"},
        {data: "NH", label: "New Hampshire"},
        {data: "NJ", label: "New Jersey"},
        {data: "NM", label: "New Mexico"},
        {data: "NV", label: "Nevada"},
        {data: "NY", label: "New York"},
        {data: "OH", label: "Ohio"},
        {data: "OK", label: "Oklahoma"},
        {data: "OR", label: "Oregon"},
        {data: "PA", label: "Pennsylvania"},
        {data: "RI", label: "Rhode Island"},
        {data: "SC", label: "South Carolina"},
        {data: "SD", label: "South Dakota"},
        {data: "TN", label: "Tennessee"},
        {data: "TX", label: "Texas"},
        {data: "UT", label: "Utah"},
        {data: "VA", label: "Virginia"},
        {data: "VT", label: "Vermont"},
        {data: "WA", label: "Washington"},
        {data: "WI", label: "Wisconsin"},
        {data: "WV", label: "West Virginia"},
        {data: "WY", label: "Wyoming"}
    ],

    emailRegExp: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$'
};